name: Python application test with Github Actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 3.12.1
              uses: actions/setup-python@v1
              with:
                python-version: 3.12.1
            - name: Install dependencies
              run: |
                make install
